### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by jensrodi** [LeoNatan/LNSwiftUIUtils#1]
I get warnings about 'featureIdentifier' and 'typeIdentifier' being deprecated in iOS 15.0. Though it still works, future support would end. Any idea how to work around this?

**Comment by LeoNatan** [comment]
This package supports iOS 14 and above, and thus has to use the legacy naming. If I recall correctly, the keys were just renamed but values are the same. So there is no risk of the API breaking. If you are using this as a package, you should not see warnings. If you are importing the code directly and seeing the warnings, fork the repo and make the changes necessary for iOS 15. Or live with the warnings.

**Comment by jensrodi** [comment]
Thanks for the fast response. I did use the code directly, not through the package, which I guess is why I got the warning. I generally try to avoid any deprecated API's as my experience tells me it'll end up causing me much more trouble in the future, when the deprecation is changed and the api is removed completely.

This is in no way criticism, I didn't realize the iOS 14 requirement. It was just a suggestion for improvement, though misunderstood. I did afterwards figure out which very simple changes needed and have it working.

**Comment by LeoNatan** [comment]
I can think of very few cases where deprecated API was outright removed. Sometimes it rots over time, but even that is relatively rare. In a simple case like this, there is very little risk. But since you are just using the code, using the modern API is simple.
